"""Editable commercial starting terms, not a promise of universal enforceability.

The electronic-consent workflow records evidence; it is not a certificate-based
digital signature. Legal reference: ICTA, Electronic Transactions Act resources:
https://www.icta.lk/digital-signature
https://www.parliament.lk/en/business-of-parliament/act-details/G5722
"""
from __future__ import annotations

from copy import deepcopy


TEMPLATE_ID = "hich-general-development-2026-10-v2"
CONSENT_TEXT = (
    "I agree to this agreement and its project schedule, confirm that I am authorised "
    "to act for the named client, and adopt my electronic signature as evidence of my agreement."
)
REVIEW_NOTE = (
    "Editable commercial template. Confirm the contracting entity, scope, rates, payment schedule, "
    "governing law and dispute forum before sending. Have local counsel review terms for the "
    "applicable jurisdiction; mandatory rights and lawful liability limits still apply."
)

# Paragraphs remain plain text so all clients and PDFs show exactly the same terms.
SECTIONS = [
    ("1. Parties, project schedule and order of priority", """This agreement is between the Hich contracting entity identified in the project schedule (the Studio) and the client identified on this agreement (the Client). The Client's representative confirms authority to approve the project, give instructions and bind the Client. The agreement reference, Client name and contact number, project name, currency and budget displayed above form part of the project schedule. The Studio's full legal name and business contact details, detailed scope, deliverables, exclusions, milestones, payment dates and any special conditions must be recorded in the accompanying accepted quotation or project schedule. Hich branding alone does not replace identification of the contracting legal entity.

An expressly agreed project-specific amendment prevails over a conflicting general clause, followed by the accepted project schedule, then these general terms. Marketing material, examples, estimates and informal discussions do not add deliverables unless incorporated in writing. An estimate is not a fixed-price commitment unless expressly identified as one. A blank or unspecified commercial item is not an unlimited service commitment; it must be agreed in writing before related work begins."""),
    ("2. General application to websites and software systems", """These terms apply, as relevant to the accepted scope, to business websites, e-commerce stores, booking and subscription platforms, web applications, dashboards, internal management systems, client portals, custom integrations, APIs, database applications and related design or maintenance services. Mention of a service category in these general terms does not mean it is included in the Client's budget. Mobile applications, desktop software, hardware, on-site installations, specialist integrations and ongoing operations are included only where expressly listed.

The project budget covers only the agreed deliverables and stated assumptions. Source data cleansing, product entry, copywriting, photography, translation, video, branding, legal policies, accessibility audits, penetration testing, load testing, third-party licences and staff training are separate unless included in the schedule. The Studio may propose practical technical substitutions where a dependency becomes unavailable, but a material change in scope or price requires written agreement."""),
    ("3. Discovery, requirements and the approved baseline", """The Client must supply accurate business rules, user roles, workflows, reports, calculations, product rules, tax requirements, integrations and acceptance criteria before development of the relevant feature. The Studio documents the agreed baseline through the quotation, requirements document, approved designs, backlog or written milestone approvals. The Client must identify a single authorised decision-maker and consolidate feedback from its stakeholders.

Work is estimated against the approved baseline. Requirements not reasonably described in that baseline are additional work, even if the Client later considers them obvious or essential. A reference website is inspiration only; copying every function, animation, page, proprietary asset or back-office process is not included unless individually specified. The Client must promptly correct misunderstandings and disclose constraints that may affect effort or lawful delivery."""),
    ("4. Changes, extra cost and written approval", """A request to add, remove, redesign or alter any approved page, workflow, feature, integration, data model, language, user role or acceptance criterion is a change request. The Studio will assess the impact on fees, milestones, dependencies and delivery dates and provide a written quotation or rate-based estimate. Additional cost is added only after the Client approves the change and associated commercial terms in writing. The Studio is not obliged to begin additional work before that approval and any agreed advance payment.

The original scope remains in effect while a change is being assessed. Reversal of a previously approved decision, redevelopment caused by inaccurate Client information, rework requested after acceptance and changes to third-party APIs or legal requirements after the baseline may require a paid change order. The Studio must identify the reason and price basis; these terms do not permit undisclosed or arbitrary charges. A revised total, payment schedule and delivery plan should be recorded against the agreement reference."""),
    ("5. Designs, revisions and content approval", """Design services include only the concepts, pages, components and revision rounds stated in the schedule. A revision refines an agreed direction; a new visual concept or a replacement of an approved design is additional scope. If the number of revisions has not been agreed, the parties must agree it before design work begins. Feedback should be specific, consolidated and supplied by the requested review date.

The Client approves names, text, prices, products, imagery, branding, links, contact details and policies before publication. The Client remains responsible for the accuracy and rights in content it supplies. The Studio will correct implementation mistakes within the agreed defect obligations, but later content replacement or strategy changes may be separately quoted. Minor display differences between supported browsers and devices are not necessarily defects when the agreed design and functionality remain substantially achieved."""),
    ("6. Client cooperation, access and dependencies", """The Client must provide timely access to domain, hosting, email, payment gateway, analytics, API, repository and other required accounts through a secure method. Where possible, access should be delegated to a separate account with the minimum required permissions. The Client must not send production passwords through an unprotected public link and must remove or rotate access when it is no longer required.

The Client is responsible for obtaining internal approvals, third-party authorisations, suitable test data and named contacts with decision-making authority. Delays caused by missing materials, unavailable systems, fragmented feedback or delayed payment may shift delivery dates and resource availability. The Studio will notify the Client of material impact. Any restart or rescheduling charge must be disclosed and agreed before it is incurred."""),
    ("7. Timelines, milestones and project pauses", """Delivery dates depend on timely Client cooperation, agreed payments and the availability of external services. A milestone is an agreed delivery stage, not a guarantee that every future enhancement is included. The Studio will use reasonable care and communicate significant risks and revised estimates. The parties must identify any genuinely fixed deadline and its assumptions in writing.

If the Client asks to pause work or fails to provide a required dependency after notice, the Studio may release the reserved development slot. Resumption depends on capacity and an agreed revised schedule. After a prolonged inactive period, the Studio may propose closure, revised estimates or a fresh agreement, with an account of work completed and amounts due. A pause does not automatically cancel payment already due for completed work or committed, approved external costs."""),
    ("8. Budget, taxes and third-party expenditure", """The displayed budget is in the stated currency and is subject to the accepted scope and payment schedule. Taxes, transaction charges and whether prices include or exclude tax must be stated in the quotation or invoice as applicable. Third-party subscriptions, domains, hosting, gateway charges, SMS/email usage, cloud resources, premium plugins, stock assets and licences are not included unless specifically listed.

The Client must approve external expenditure in advance or under a written spending allowance. Vendor pricing and exchange rates may change; the Studio will disclose material changes before new commitments. Vendor costs are reimbursable only as agreed and supported by the relevant billing details. The Studio does not guarantee that a free tier or promotional price will remain available throughout the lifetime of the system."""),
    ("9. Deposits, invoices and payment", """The required advance, milestone amounts, invoice due dates and accepted payment methods are those shown in the accepted schedule and invoices. Work may be scheduled only after the agreed advance clears. An advance is applied to the project price; any refund on cancellation is determined by work performed, approved commitments and applicable law, rather than an automatic blanket forfeiture.

The Client should raise a specific invoice dispute promptly and pay undisputed amounts by their due dates. The Studio will investigate discrepancies and issue a corrected invoice where necessary. Interest or late fees apply only if expressly agreed in advance and lawful. Production deployment, source handover, licence activation or transfer of rights may depend on payment of the corresponding undisputed amounts. An invoice amendment does not by itself alter an already signed agreement; changes to the contract require an approved amendment or change order."""),
    ("10. Non-payment and suspension", """If an undisputed payment is overdue, the Studio may give written notice identifying the amount, remedial deadline and proposed suspension. Subject to applicable law and the agreed notice period, the Studio may pause new work or Studio-provided services if payment remains overdue. Emergency suspension may be appropriate for an immediate security threat, unlawful activity or a vendor-mandated restriction; the Studio will explain the reason as soon as reasonably practicable.

Suspension is not authority to destroy Client data, unlawfully withhold Client-owned property or interfere with unrelated services. The Studio will take reasonable care when suspending services under its control and provide reasonable export or recovery arrangements where required. Restoration may require cleared payment, resolution of the cause and separately approved reinstatement work. Vendor-imposed cancellation or retention limits may affect recovery."""),
    ("11. Remote meetings, site visits and travel fees", """Services are delivered remotely unless an on-site visit is expressly included. Discovery visits, office meetings, installation, demonstrations, on-site training and support visits may be charged separately. Before a visit is confirmed, the Studio must disclose the visit fee or hourly rate, minimum booking period, travel time treatment, mileage or transport cost, accommodation and other reasonable expenses, and obtain written Client approval.

Travel outside the agreed service area, additional attendees, waiting time caused by unavailable personnel or equipment, and out-of-hours visits may incur additional approved charges. Cancellation and rescheduling fees apply only where disclosed and accepted when booking; unavoidable vendor charges should be supported by evidence. A request for an urgent visit does not create a response-time guarantee. Remote diagnosis may be required before an on-site booking."""),
    ("12. Domains, ownership and renewals", """The Client should be recorded as the domain registrant where permitted by registrar rules, using accurate contact details and an email address it controls. Domain availability is not guaranteed until registration succeeds. Registration, renewal, privacy services and premium domain fees are separate unless included. The Client is responsible for keeping registrant details current and paying renewals on time, except to the extent the Studio expressly accepts a managed renewal obligation in writing.

Registrar verification, transfer locks, registry rules, disputes and suspension policies remain outside the Studio's control. The Studio is not responsible for loss caused solely by the Client's failure to approve or fund renewal after appropriate notice. The Studio remains responsible for its own agreed obligations and legally actionable conduct. Trademark clearance and recovery of a domain from a third party are not included development services."""),
    ("13. Domain changes, registrar transfers and DNS", """Changing a domain name, moving a registrar, altering nameservers or transferring hosting after approval is a separate technical change unless included in the schedule. The Studio will assess and quote for backups, DNS records, SSL certificates, redirects, email records, application configuration, payment gateway allowlists, analytics, verification and testing. The Client must approve the fee, maintenance window and possible service impact before work begins.

DNS propagation and registry or provider restrictions can delay completion. Domain changes may affect search indexing, email delivery, saved links and integrations; rankings and third-party caches cannot be guaranteed. The Client must provide proof of control and authorisation for any transfer. Client-owned domain credentials or transfer codes will be released subject to lawful verification and applicable registrar requirements; a payment dispute must not be used to unlawfully take ownership of the Client's domain. Reversal of a completed migration may require separately approved work."""),
    ("14. Hosting, infrastructure and service availability", """Hosting capacity, locations, storage, bandwidth, resource limits, backup frequency, support coverage and any availability target must be set out in the hosting or maintenance schedule. Without that schedule, this development agreement does not promise continuous hosting, unlimited traffic, 24-hour monitoring or a service-level credit. Infrastructure may require upgrades as traffic, data volume or business processes grow.

Planned maintenance will be communicated where reasonably possible. External outages, network failures, vendor suspensions and attacks may affect availability despite reasonable precautions. The Studio will assist within the agreed support scope and escalate vendor issues where it controls the account. Extraordinary incident response, migration or capacity engineering may require a separate approved quotation unless required to remedy a breach of the Studio's existing obligations."""),
    ("15. E-commerce, payments and regulated functions", """The Client is the merchant and remains responsible for its products, prices, stock, tax treatment, shipping rules, refunds, chargebacks, consumer disclosures and lawful trading. Payment gateway, bank, marketplace and identity verification approvals are third-party decisions. The Studio does not guarantee merchant approval, settlement timing, a particular conversion rate or freedom from fraudulent transactions.

The agreed scope must state supported payment methods, tax calculations, currencies, shipping regions and integrations. Payment card handling should use approved hosted or tokenised services; storing sensitive card data is excluded unless expressly agreed under a suitable compliance programme. The Client must obtain specialist advice for financial, medical, educational or other regulated workflows. Development services alone do not certify regulatory compliance."""),
    ("16. Integrations, licences and external platforms", """The Client must maintain valid licences and accounts for third-party software and services needed by the project. Open-source and commercial components remain subject to their own licences and terms. The Studio will identify material licensing requirements within the agreed deliverables and must not promise ownership of rights it does not possess.

Vendors can change APIs, pricing, permissions, app-review policies and compatibility. Work needed because of a later vendor change is additional maintenance unless included in the support schedule. The Studio will explain the impact and obtain approval for additional cost. The Studio is not responsible for a third party's independent failure, but remains responsible for reasonable care in its own selection, configuration and implementation within the agreed scope."""),
    ("17. Testing, acceptance and launch approval", """The Studio will make each relevant milestone available for review against its agreed acceptance criteria. The Client should provide one consolidated list of reproducible defects within the acceptance period stated in the schedule. If no period is stated, the parties should agree a reasonable review period before delivery. A defect is a failure to meet an agreed requirement; a new preference or additional capability is a change request.

The Studio will remedy substantiated in-scope defects within a reasonable time, taking severity into account. Minor issues that do not materially prevent agreed use may be tracked for correction without indefinitely delaying an otherwise accepted milestone. Silence alone does not establish unlimited acceptance or waive non-excludable rights. Production launch requires the Client's written approval, or another launch mechanism expressly accepted in the schedule. Client use and written milestone approvals may be recorded as evidence of acceptance."""),
    ("18. Content, intellectual property and handover", """The Client retains ownership of its pre-existing materials and grants the Studio the permissions reasonably needed to perform the services. Subject to full payment of amounts due for the relevant deliverables, the Client receives the ownership or licence to custom work expressly described in the project schedule. The schedule should identify source-code delivery, repository access, design files, documentation, deployment configuration and account handover. A website purchase does not automatically include all internal tools or proprietary frameworks used to create it.

The Studio retains its pre-existing code, reusable components, methods, generic know-how and tools, while granting the licence reasonably necessary to use them as embedded in the paid deliverables, as set out in the schedule. Third-party components remain governed by their licences. The Studio may not reuse the Client's confidential information or proprietary content. Credentials must be handed over securely, and the Client should replace shared secrets after handover."""),
    ("19. Warranty, defects and maintenance boundaries", """Any defect correction period and its start date must be stated in the project schedule. During that period, the Studio will correct reproducible failures of the delivered work to meet the agreed scope, subject to the schedule and mandatory legal rights. A correction period is not an unlimited enhancement, content-management or technical-support subscription.

Issues caused by unauthorised modifications, unsupported environments, misuse, inaccurate Client data, vendor changes or later security threats may fall outside the included correction scope. The Studio must explain the cause and quote additional work before charging. Ongoing updates, backups, monitoring, compatibility testing, new features and emergency availability require a maintenance plan unless expressly included. Nothing in this clause removes a remedy that applicable law does not allow the parties to exclude."""),
    ("20. Support, training and response expectations", """Support channels, business hours, included hours, training sessions and severity definitions must be specified in the support schedule. A response target is an acknowledgement target unless a resolution commitment is expressly stated. Resolution depends on diagnosis, access and third-party cooperation. Messages to individual staff or personal social accounts may not enter the support queue; the Client should use the agreed channel.

Extra training, replacement staff onboarding, new documentation, data entry and assistance with the Client's own hardware or internet connection may be separately quoted. Emergency or out-of-hours work requires availability and advance agreement on rates, except for steps the Studio is already legally or contractually obliged to take. The Studio will not bill for correcting its own breach merely by labelling the work additional support."""),
    ("21. Security, privacy and personal data", """The parties must agree their respective privacy roles, authorised processing purposes, data categories, retention periods and any required processing agreement before production personal data is supplied. The Client is responsible for a lawful basis, accurate notices and its own instructions. The Studio will implement the security measures agreed for the project and apply reasonable professional care, including appropriate access controls and handling of credentials.

No internet system is guaranteed immune from every attack. The Client must maintain secure administrator accounts, use multi-factor authentication where available and avoid sharing credentials. Each party will promptly notify the other of a relevant security incident and cooperate in containment, evidence preservation and any legally required notifications. Hosting location, international transfers and subprocessors must be addressed where applicable. Security audits or compliance certifications are separate unless explicitly included."""),
    ("22. Backups, migration and data recovery", """Before a migration, deployment or major change, the parties must identify who creates, verifies and retains backups and agree a rollback plan appropriate to the risk. A backup is useful only if it can be restored; any included restore testing must be specified. The Client should retain independent copies of essential business data, subject to its security obligations.

Data migration scope must state source formats, volume, mapping rules, validation samples and excluded history or attachments. The Client must validate migrated business information and retain the source until acceptance. Recovery of corrupted legacy data or reconstruction after a third-party failure is additional work unless the Studio is already responsible for the loss. These obligations do not excuse a party's negligence or override any non-excludable liability."""),
    ("23. Confidentiality and project publicity", """Each party must protect the other's non-public commercial, technical and personal information using reasonable safeguards and disclose it only to people who need it to perform the agreement and are bound by suitable duties. Information that becomes public without breach, is independently developed or is lawfully obtained elsewhere is not confidential. Legally compelled disclosure should be preceded by notice where permitted.

The Studio may engage suitable employees and subcontractors while remaining responsible for its contractual obligations and confidentiality arrangements. Public portfolio display, screenshots, Client logos, testimonials and case studies require the Client's written permission unless a specific publicity licence has been expressly agreed. Confidential business data, administrator screens and customer information must not be exposed in demonstrations."""),
    ("24. Client materials, prohibited uses and claims", """The Client confirms it has the rights and permissions to supply its content, trademarks, datasets and instructions, and must not require unlawful, deceptive or infringing features. The Studio may decline or suspend work that reasonably appears unlawful, with an explanation and an opportunity to resolve the issue where appropriate. The Studio must not knowingly introduce unlicensed assets or malicious code.

Where lawful and reasonable, the Client will be responsible for third-party claims caused by infringing materials or unlawful instructions it supplied, to the extent attributable to the Client. The Studio must notify the Client promptly, allow reasonable participation in the defence and not settle an obligation on the Client without consent. This responsibility does not extend to claims caused by the Studio's own unauthorised conduct, negligence or modifications outside the Client's instructions."""),
    ("25. Performance, search and business outcomes", """Any performance target must specify the environment, test method, data volume and external dependencies. Search-engine rankings, traffic, revenue, customer acquisition, uninterrupted third-party delivery and business profitability depend on factors beyond development and are not guaranteed. Search optimisation, advertising, analytics interpretation and conversion testing are included only to the stated extent.

The Studio will perform the agreed work with reasonable skill and care. The Client should validate critical calculations, business processes and operational procedures before relying on the system in production. Demonstrations, prototypes and test environments are not production-ready unless expressly delivered as such. Any use of automated or AI-generated features requires the human review and safeguards identified in the scope."""),
    ("26. Liability and legally protected rights", """Subject to applicable law and the exceptions below, any agreed monetary liability cap and exclusions of indirect loss must be expressly recorded in the project schedule and be reasonable in the circumstances. If no lawful cap has been agreed, this template does not invent one. The parties should consider the project value, foreseeable risks, insurance and their ability to prevent loss when agreeing a cap.

No clause excludes or limits liability for fraud, deliberate misconduct, death or personal injury caused by negligence where prohibited, or any other liability or consumer remedy that the applicable law does not permit to be excluded or restricted. Confidentiality, data protection and intellectual property claims must be treated consistently with applicable law and the agreed risk allocation. Each party must take reasonable steps to mitigate avoidable loss. A party is responsible only to the extent legally attributable to its conduct and obligations."""),
    ("27. Termination, cancellation and orderly exit", """Either party may end the agreement for a material breach that is not remedied within the written cure period agreed in the schedule or, if none is stated, a reasonable period after detailed notice. Immediate termination may be available for a serious unlawful act or other circumstances permitted by law. Convenience cancellation rights and any notice period must be stated in the schedule.

On termination the parties will account for completed work, authorised work in progress, approved non-cancellable commitments and payments already made. Any unused balance owed to the Client must be returned as required by the agreement and applicable law. The Studio will provide an orderly handover of paid deliverables and Client-owned materials within the agreed exit scope. Extra migration or transition assistance may be charged only at agreed rates. Retention or deletion of remaining data must follow lawful obligations and the agreed retention schedule."""),
    ("28. Events beyond reasonable control", """A party affected by a genuine event beyond its reasonable control must promptly notify the other, explain the expected impact and take reasonable steps to reduce disruption. Examples may include natural disasters, widespread utility failures or binding government restrictions, depending on the circumstances. Ordinary lack of funds or a preventable failure to maintain an agreed service is not automatically an excused event.

Affected obligations may be rescheduled for a reasonable period, but obligations already due and unaffected by the event remain in force. If disruption continues for the period agreed in the schedule, the parties should agree a revised plan or a lawful termination and accounting of completed work. This clause does not provide a blanket release from all responsibility."""),
    ("29. Notices, records and dispute resolution", """The parties will use the business email addresses and other written channels identified in the project schedule for approvals, change orders, invoices and notices. The Client must keep its contact details current. Important contractual notices should identify the agreement reference and request acknowledgement; a messaging delivery icon alone is not conclusive evidence of receipt.

The parties should first attempt good-faith resolution through their authorised representatives. Any mediation, arbitration, governing law and court jurisdiction must be expressly specified in the project schedule; this general template does not assume a country or compel arbitration without agreement. Mandatory consumer, privacy and other applicable laws continue to apply. Urgent protective relief and non-waivable statutory rights are not prevented by an informal discussion process."""),
    ("30. Electronic agreement, signature and retained copy", """The Client may review the complete agreement and project details before signing and should ask for clarification where needed. The signing form records the signer's name, job role, affirmative consent and chosen typed or drawn electronic signature, along with the agreement version, server timestamp and supporting request metadata. The signer adopts that signature to express agreement and confirms authority to sign for the Client. No representation is made that a typed or drawn signature is a certificate-backed digital signature or an independently verified identity.

The signed version is preserved as a fixed record. Later changes to commercial terms require a new agreement or mutually approved amendment; an administrator cannot silently replace the signed terms. The Client can retain the signed copy supplied through the secure link. Anyone with a private link may be able to view the document, so the parties should share it only with intended recipients. Applicable law determines the legal effect of the electronic record and any required signing formalities."""),
    ("31. Entire agreement, assignment and severability", """This agreement and the expressly incorporated schedule contain the parties' agreement on the described services. Amendments require recorded mutual approval by authorised representatives. A failure to exercise a right immediately is not automatically a waiver. If a clause is unlawful or unenforceable, it is limited or severed only to the extent permitted, and the remaining lawful terms continue where possible.

Neither party may transfer obligations in a way that materially prejudices the other without consent, except as allowed by an expressly agreed clause or applicable law. Nothing creates an employment relationship, partnership or agency beyond authority specifically granted. Clauses concerning accrued payments, confidentiality, intellectual property, lawful liability allocation and retained evidence survive termination to the extent necessary for their purpose."""),
]

SECTIONS.extend([
    ("32. Hich Web visiting fee and final-balance credit", "Where an on-site visit is requested, Hich Web quotes a visiting fee between LKR 5,000 and LKR 15,000 according to location, duration and required personnel. The exact accepted amount is recorded in the project-specific commercial schedule and must be paid before the visit is confirmed. The fee is non-refundable once the agreed visit is delivered or the Client cancels the reserved visit, subject to mandatory rights and reasonable treatment of an unperformed visit cancelled by Hich Web. The collected fee is credited once against the project's final balance; it is part of the project price and must not be billed or deducted twice. No credit is posted merely because a booking was created. For a foreign-currency project, the parties agree the conversion rate and credit in writing. Additional visits and travel costs require a separate accepted quotation."),
    ("33. Transfer quotations at current rates", "Domain registrar, hosting, email, repository and project transfers are priced by Hich Web at the rates and exchange rate applicable when the transfer quotation is prepared. The quotation identifies vendor transfer or renewal charges, migration labour, backups, testing, licence restrictions, tax treatment, exclusions and its validity period. A fixed historic development budget does not freeze future transfer prices. The Client must approve the current quotation and fund agreed charges before transfer work starts. Hich Web does not impose undisclosed charges and does not guarantee vendor acceptance, immediate DNS propagation or continued availability of an expired domain. Lawful verification and payment for the relevant agreed work apply to handover, while Client ownership and mandatory rights remain protected."),
    ("34. Renewal deadlines and disclosed late charges", "Domain, hosting and related renewal dates shown in the schedule are separate from development invoice deadlines. Renewal requires cleared payment and vendor confirmation before expiry; reminders assist the Client but do not extend vendor deadlines. Expired services may be suspended, enter redemption or become unavailable. Recovery, reinstatement and changed vendor prices are quoted separately. If a lawful 18% late-payment surcharge is expressly accepted in the project schedule, it is calculated once on the unpaid renewal base after the agreed due date, itemised separately and does not compound. It is not VAT and is not imposed retrospectively without agreement. VAT or another statutory tax is invoiced only where legally applicable, using the required registration and invoice details; tax does not arise solely because payment is late."),
    ("35. Payment evidence and authorised changes", "Payments count only after cleared funds are recorded against the relevant invoice. The Client supplies the invoice reference and transfer receipt; a screenshot alone does not prove cleared payment. Mid-project and final payments reduce the same project balance. Hich Web provides corrected receipts when a posting error is substantiated, retains an audit trail and does not silently erase payment history. Work, production release and transfer of agreed deliverables may be conditional on corresponding undisputed payments. Extra work, third-party cost increases and changes to an accepted payment schedule require written approval. No clause excludes liability or mandatory remedies that cannot lawfully be excluded."),
])

GENERAL_AGREEMENT = "\n\n".join(f"{heading}\n\n{body}" for heading, body in SECTIONS)
PROJECT_OVERVIEW = (
    "Development of the project identified above, as itemised in the accepted quotation and "
    "written project schedule. Only the expressly listed deliverables are included in the project budget."
)
_DEFAULT_TERMS = {
    "Contracting entity": "Hich — full legal entity and business contact to be specified in the accepted project schedule.",
    "Scope and deliverables": "As itemised in the accepted quotation and project schedule; additional requirements require written approval of extra cost and timing.",
    "Payment schedule": "As expressly agreed in the accepted quotation and invoices before work begins.",
    "Visit and travel fees": "LKR 5,000–15,000 as accepted in the commercial schedule, collected before a visit, non-refundable subject to the visiting-fee clause and mandatory rights, and credited once to the final project balance.",
    "Domain and hosting changes": "Hich Web determines the quotation using current vendor, hosting and project-transfer rates; written approval is required before work begins.",
    "Support and defect period": "Only the coverage and period expressly stated in the project schedule.",
    "Governing law and dispute forum": "To be expressly agreed in the project schedule; mandatory applicable law continues to apply.",
}


def default_terms() -> dict[str, str]:
    return deepcopy(dict(SECTIONS) | _DEFAULT_TERMS)


def template_payload() -> dict:
    return {
        "id": TEMPLATE_ID,
        "title": "General Website & System Development Agreement",
        "description": PROJECT_OVERVIEW,
        "terms": default_terms(),
        "consent_text": CONSENT_TEXT,
        "sections": [heading for heading, _ in SECTIONS],
        "review_note": REVIEW_NOTE,
    }
